#!/usr/bin/env python3
# _*_ coding: utf8 _*_
class Student(object):
    def __init__(self, name, score):
        self.__name = name
        self.__score = score
    def print_score(self):
        print('%s %s'%(self.__name,self.__score))
    def get_grade(self):
        if self.score >= 90:
            return 'A'
        elif self.score >= 60:
            return 'B'
        else:
            return 'C'
    def get_name(self):
        return self.__name
    def get_score(self):
        return sefl.__score
    def set_score(self, score):
        if 0 <= score <= 100:
            self.__score = 100
        else:
            raise ValueError('bad input score')
