#!/usr/bin/env python3
# _*_ coding: utf8 _*_

class Animal(object):
    name = 'total animal'
    def run(self):
        print("animal is running")

class Dog(Animal):
    def run(self):
        print("dog is running")
    def run_twice(self,animal):
        animal.run()
        animal.run()
        
class Cat(Animal):
    def run(self):
        print("cat is running")


class Tortoise(Animal):
    def run(self):
        print("Tortoise is running slowly")
def run_twice(animal):
	animal.run()
	animal.run()


class Myobject(object):
    def __init__(self):
        self.x = 23
    def power(self):
        return self.x * self.x
    def print(self):
        print("test")

class Stu(object):
    pass

class Student(object):
    __slots__ = ('name', 'age')

class SubStu(Student):
    pass

class Student_1(object):
    def get_score(self):
        return self._score
    def set_score(self, value):
        if not isinstance(value,int):
            raise ValueError('source must be integer!')
        if value < 0 or value > 100:
            raise ValueError('score must be in the range of 0 to 100')
        self.score = value
